name: Deploy

on:
  workflow_dispatch:
    inputs:
      skip-npm:
        type: boolean
        description: Skip NPM release
      skip-directory:
        type: boolean
        description: Skip directory website deployment
      # pre-release:
      #   type: boolean
      #   description: Create a pre-release
  release:
    types: [created]

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    if: github.event.inputs.skip-npm != 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent

      - name: Publish to NPM
        if: github.event.inputs.pre-release != 'true'
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Publish pre-release to NPM
      #   if: github.event.inputs.pre-release = 'true'
      #   run: yarn prerelease
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  directory:
    name: Directory website
    runs-on: ubuntu-latest
    if: github.event.inputs.skip-directory != 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
        working-directory: packages/directory

      - name: Build directory
        run: yarn build
        working-directory: packages/directory

      - name: Publish static assets to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: packages/directory/build
